### PR TITLE
Adding all lab files

### PR DESCRIPTION
**Pull request by bsmthal**
Just an initial merge. I'll be going back to add more comments to my code, at the request of Eric.

### CODE REVIEW

**Comment by philipbl** [comment]
Add .pio folder to your .gitignore file. As a general rule, you don't want to version control machine generated files.

**Comment by philipbl** [comment]
I thought PIO added the .gitignore file for you. This is what my .gitignore file has for a PIO project:

```
.pio
.vscode/.browse.c_cpp.db*
.vscode/c_cpp_properties.json
.vscode/launch.json
.vscode/ipch
```

Use this for your .gitignore.

**Comment by bsmthal** [comment]
So I should remove .pio from the repository now, right?

**Comment by philipbl** [comment]
It might just be easier to start over. There is a command that will allow you to ignore the files, but they will still be in the git history. There are commands to remove those files through all of your history, but it might be easier just to start over at this point. Clone the repo again, copy over the files (including the .gitignore), commit, and submit a PR. I am happy to help you with this.

**Pull request closed without merging**
